apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world-service
  namespace: default
spec:
  ports:
  - nodePort: 30338
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  type: LoadBalancer