version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.1
jobs:
  my-java:
    docker:
      - image: cimg/openjdk:17.0.0
    steps:
      - checkout
      - run: java HelloWorld.java
      - kubernetes/install
      - run: kubectl --kubeconfig=config apply -f helloworld.yaml
workflows:
  JAVA-workflow:
    jobs:
      - my-java
